apiVersion: v1
kind: PersistentVolume
metadata:
  name: zalenium-videos
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: "/tmp/videos"